### ISSUE TITLE
Get<T>(Type class)

### ISSUE THREAD

**Issue by agausachs** [Keswiik/Juicy#24]
Hi!

First, thank you for this excellent work. I'm trying to integrate Juicy in one of my projects, that it's a port from a Java app.

The Java app uses Guice, so your library makes easy the code migration. 

The only difference I found until now it's trying to apply Guice's:
`Main.getInjector().getInstance(implentationClass)` where implentationClass is a `"Class<? extends IMyInterface>"`

implentationClass is a parameter of the method that uses this code line like that:

```
private final void addHandlers(ChannelPipeline pipeline, Class<? extends ChannelHandler>... handlerClasses) {
        for (Class<? extends ChannelHandler> handlerClass : handlerClasses) {
            if (handlerClass != null) {
                pipeline.addLast(Main.getInjector().getInstance(handlerClass));
            }
        }
    }
```

Due to .NET restrictions I can't do this:
`Main.GetInjector().Get<typeof(implentationClass)>`

Is there any way to do this with Juicy? I have tried `GetInjector().Get<IMyInterface>(implementationClass) `but Get only has a overload for a string.

Thank you!

**Comment by Keswiik** [comment]
Sorry for the extremely late response, didn't think anyone was actually using this.

While .Net doesn't allow `Main.GetInjector().Get<typeof(implentationClass)>`, you can however make use of the `MethodInfo#MakeGenericMethod` to apply your type arguments before call it using `MethodInfo#Invoke`.

This is more of a bandaid approach, though. A non-generic method to the injector that allows for type parameters could be added to the injector.
